#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'java'
cookbook 'git'
cookbook 'subversion'
cookbook 'ant'
cookbook 'maven'
cookbook 'gradle'
cookbook 'nodejs'
cookbook 'mongodb'
cookbook 'virtualbox'
cookbook 'vagrant'
